import {
  SALES_ERP_SCHEMA_VERSION,
  type SalesErpBootstrapPayloadByResource,
  type SalesErpBootstrapResource,
  type SalesErpEvent,
} from "./contracts";

export type SalesErpMockDataset = {
  [K in SalesErpBootstrapResource]: SalesErpBootstrapPayloadByResource[K][];
};

const sourceUpdatedAt = "2026-07-16T10:00:00.000Z";

const customers: SalesErpMockDataset["customers"] = [
  {
    externalId: "mock-customer-be-001",
    sourceVersion: "mock-v1",
    sourceUpdatedAt,
    relationType: "CUSTOMER",
    status: "ACTIVE",
    legalName: "Demo Veiligheid Brussel",
    displayName: "Demo Brussel",
    vatNumber: "BE0000000097",
    preferredLanguage: "nl",
    scope: { country: "BE", representativeExternalId: "mock-rep-be-001", teamExternalId: "mock-team-be" },
    contacts: [
      {
        externalId: "mock-contact-be-001",
        sourceVersion: "mock-v1",
        sourceUpdatedAt,
        type: "PERSON",
        name: "Demo Contact België",
        email: "belgie@example.invalid",
        primary: true,
        active: true,
      },
    ],
    addresses: [
      {
        externalId: "mock-address-be-001",
        sourceVersion: "mock-v1",
        sourceUpdatedAt,
        type: "LEGAL",
        street: "Voorbeeldstraat",
        houseNumber: "1",
        postalCode: "1000",
        city: "Brussel",
        country: "BE",
        primary: true,
        active: true,
      },
    ],
    billingValidation: { status: "VALID", modulo97Valid: true, viesCheckedAt: sourceUpdatedAt },
    isDemo: true,
  },
  {
    externalId: "mock-customer-nl-001",
    sourceVersion: "mock-v1",
    sourceUpdatedAt,
    relationType: "CUSTOMER",
    status: "ACTIVE",
    legalName: "Demo Veiligheid Nederland",
    displayName: "Demo Nederland",
    preferredLanguage: "nl",
    scope: { country: "NL", representativeExternalId: "mock-rep-nl-001", teamExternalId: "mock-team-nl" },
    contacts: [],
    addresses: [
      {
        externalId: "mock-address-nl-001",
        sourceVersion: "mock-v1",
        sourceUpdatedAt,
        type: "LEGAL",
        street: "Voorbeeldweg",
        houseNumber: "2",
        postalCode: "1011 AA",
        city: "Amsterdam",
        country: "NL",
        primary: true,
        active: true,
      },
    ],
    billingValidation: { status: "NOT_CHECKED" },
    isDemo: true,
  },
  {
    externalId: "mock-customer-de-001",
    sourceVersion: "mock-v1",
    sourceUpdatedAt,
    relationType: "CUSTOMER",
    status: "ACTIVE",
    legalName: "Demo Sicherheit Deutschland",
    displayName: "Demo Deutschland",
    preferredLanguage: "de",
    scope: { country: "DE", representativeExternalId: "mock-rep-de-001", teamExternalId: "mock-team-de" },
    contacts: [],
    addresses: [
      {
        externalId: "mock-address-de-001",
        sourceVersion: "mock-v1",
        sourceUpdatedAt,
        type: "LEGAL",
        street: "Beispielstraße",
        houseNumber: "3",
        postalCode: "10115",
        city: "Berlin",
        country: "DE",
        primary: true,
        active: true,
      },
    ],
    billingValidation: { status: "NOT_CHECKED" },
    isDemo: true,
  },
];

const appointments: SalesErpMockDataset["appointments"] = customers.map((customer, index) => ({
  externalId: `mock-appointment-${customer.scope.country.toLowerCase()}-001`,
  sourceVersion: "mock-v1",
  sourceUpdatedAt,
  businessDate: "2026-07-20",
  startsAt: `2026-07-20T0${8 + index}:00:00.000Z`,
  endsAt: `2026-07-20T${10 + index}:00:00.000Z`,
  timeZone: "Europe/Brussels",
  sequence: 1,
  status: "PLANNED",
  customerExternalId: customer.externalId,
  representativeExternalId: customer.scope.representativeExternalId ?? "mock-rep",
  teamExternalId: customer.scope.teamExternalId,
  country: customer.scope.country,
}));

const article = {
  externalId: "mock-article-ehbo-001",
  sourceVersion: "mock-v1",
  sourceUpdatedAt,
  articleNumber: "MOCK-EHBO-001",
  stemNumber: "MOCK-EHBO",
  descriptionNl: "Demo EHBO-koffer",
  descriptionFr: "Trousse de secours démo",
  descriptionDe: "Demo-Erste-Hilfe-Koffer",
  unit: "ST",
  vatRate: "21.00",
  active: true,
  carrierBound: true,
  lotTrackingRequired: true,
  expiryTrackingRequired: true,
  prices: (["BE", "NL", "DE"] as const).map((country) => ({
    externalId: `mock-price-${country.toLowerCase()}-001`,
    sourceVersion: "mock-v1",
    sourceUpdatedAt,
    country,
    currency: "EUR" as const,
    type: "SALES" as const,
    amount: "49.95",
    validFrom: "2026-01-01",
  })),
} satisfies SalesErpMockDataset["articles"][number];

const referenceBase = {
  sourceVersion: "mock-v1",
  sourceUpdatedAt,
  active: true,
};

export const salesErpMockDataset: SalesErpMockDataset = {
  customers,
  appointments,
  articles: [article],
  commercialHistory: [
    {
      externalId: "mock-invoice-be-001",
      sourceVersion: "mock-v1",
      sourceUpdatedAt,
      documentType: "INVOICE",
      documentNumber: "MOCK-INV-0001",
      documentDate: "2026-06-30",
      customerExternalId: "mock-customer-be-001",
      representativeExternalId: "mock-rep-be-001",
      currency: "EUR",
      amountExcludingVat: "49.95",
      amountIncludingVat: "60.44",
      paymentStatus: "PAID",
      openAmount: "0.00",
      lines: [
        {
          lineNumber: 1,
          articleExternalId: article.externalId,
          articleNumberSnapshot: article.articleNumber,
          descriptionSnapshot: article.descriptionNl,
          quantity: "1.000",
          unitSnapshot: "ST",
          unitPriceSnapshot: "49.95",
          vatRateSnapshot: "21.00",
          lineAmountExcludingVat: "49.95",
        },
      ],
    },
  ],
  replenishments: [
    {
      externalId: "mock-replenishment-be-001",
      sourceVersion: "mock-v1",
      sourceUpdatedAt,
      shipmentNumber: "MOCK-SHIP-0001",
      status: "IN_TRANSIT",
      country: "BE",
      representativeExternalId: "mock-rep-be-001",
      shippedAt: "2026-07-16T08:00:00.000Z",
      lines: [
        {
          externalId: "mock-replenishment-line-001",
          articleExternalId: article.externalId,
          articleNumberSnapshot: article.articleNumber,
          expectedQuantity: "5.000",
          unitSnapshot: "ST",
          lotNumber: "MOCK-LOT-001",
          expiryDate: "2027-12-31",
        },
      ],
    },
  ],
  cashBalances: [
    {
      externalId: "mock-cash-balance-be-001",
      sourceVersion: "mock-v1",
      sourceUpdatedAt,
      representativeExternalId: "mock-rep-be-001",
      country: "BE",
      currency: "EUR",
      balance: "0.00",
      lastDepositConfirmedAt: "2026-07-13T07:00:00.000Z",
    },
  ],
  appointmentOutcomeReasons: [
    {
      ...referenceBase,
      externalId: "mock-outcome-reason-closed",
      code: "CLOSED",
      labelNl: "Klant gesloten",
      labelFr: "Client fermé",
      labelDe: "Kunde geschlossen",
      requiresComment: false,
    },
    {
      ...referenceBase,
      externalId: "mock-outcome-reason-other",
      code: "OTHER",
      labelNl: "Andere reden",
      labelFr: "Autre raison",
      labelDe: "Anderer Grund",
      requiresComment: true,
    },
  ],
  documentCategories: [
    {
      ...referenceBase,
      externalId: "mock-document-category-photo",
      code: "PHOTO",
      labelNl: "Foto",
      labelFr: "Photo",
      labelDe: "Foto",
      requiresComment: false,
    },
  ],
  paymentMethods: [
    {
      ...referenceBase,
      externalId: "mock-payment-method-cash",
      code: "CASH",
      labelNl: "Contant",
      labelFr: "Espèces",
      labelDe: "Bar",
      requiresComment: false,
      affectsCashBalance: true,
    },
    {
      ...referenceBase,
      externalId: "mock-payment-method-card",
      code: "CARD",
      labelNl: "Kaart",
      labelFr: "Carte",
      labelDe: "Karte",
      requiresComment: false,
      affectsCashBalance: false,
    },
  ],
  customerLocations: [
    {
      externalId: "mock-location-be-001",
      sourceVersion: "mock-v1",
      sourceUpdatedAt,
      customerExternalId: "mock-customer-be-001",
      type: "LOCATION",
      name: "Demo magazijn",
      archived: false,
    },
    {
      externalId: "mock-carrier-be-001",
      sourceVersion: "mock-v1",
      sourceUpdatedAt,
      customerExternalId: "mock-customer-be-001",
      parentLocationExternalId: "mock-location-be-001",
      type: "CARRIER",
      name: "Demo EHBO-koffer inkomhal",
      linkedArticleExternalId: article.externalId,
      archived: false,
    },
  ],
  carrierBalances: [
    {
      externalId: "mock-carrier-balance-be-001",
      sourceVersion: "mock-v1",
      sourceUpdatedAt,
      carrierExternalId: "mock-carrier-be-001",
      articleExternalId: article.externalId,
      quantity: "2.000",
      unit: "ST",
      lotNumber: "MOCK-LOT-001",
      expiryDate: "2027-12-31",
    },
  ],
};

export const salesErpMockEvents: SalesErpEvent[] = [
  {
    schemaVersion: SALES_ERP_SCHEMA_VERSION,
    provider: "MOCK",
    messageId: "mock-event-customer-be-001",
    eventType: "customer.upserted",
    entityExternalId: customers[0].externalId,
    sourceVersion: customers[0].sourceVersion,
    occurredAt: sourceUpdatedAt,
    payload: customers[0],
  },
  {
    schemaVersion: SALES_ERP_SCHEMA_VERSION,
    provider: "MOCK",
    messageId: "mock-event-appointment-be-001",
    eventType: "appointment.upserted",
    entityExternalId: appointments[0].externalId,
    sourceVersion: appointments[0].sourceVersion,
    occurredAt: sourceUpdatedAt,
    payload: appointments[0],
  },
  {
    schemaVersion: SALES_ERP_SCHEMA_VERSION,
    provider: "MOCK",
    messageId: "mock-event-article-001",
    eventType: "article.upserted",
    entityExternalId: article.externalId,
    sourceVersion: article.sourceVersion,
    occurredAt: sourceUpdatedAt,
    payload: article,
  },
];
