ALTER TABLE `HelpRequest`
  MODIFY `status` ENUM(
    'NIEUW',
    'OPEN',
    'IN_BEHANDELING',
    'VERVOLGACTIE_GEPLAND',
    'BEGELEIDING',
    'CONTACTMOMENT',
    'RETRAINING',
    'SALESTRAINING',
    'GESLOTEN',
    'INGETROKKEN',
    'AFGESLOTEN',
    'GEANNULEERD'
  ) NOT NULL DEFAULT 'OPEN';
