INSERT INTO `Permission` (`id`, `key`, `label`, `group`, `description`, `createdAt`, `updatedAt`) VALUES
  ('perm_menu_coaching_enabled', 'menu.coaching.enabled', 'Coaching tonen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_dashboard', 'menu.coaching.dashboard', 'Dashboard', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_planning', 'menu.coaching.planning', 'Planning', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_coachings', 'menu.coaching.coachings', 'Begeleidingen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_my_team', 'menu.coaching.myTeam', 'Mijn Team', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_action_points', 'menu.coaching.actionPoints', 'Actiepunten', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_reporting', 'menu.coaching.reporting', 'Rapportering', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_users', 'menu.coaching.users', 'Gebruikers', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_modules', 'menu.coaching.modules', 'Modules', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_coaching_roles', 'menu.coaching.roles', 'Rollen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_salesday_enabled', 'menu.salesday.enabled', 'Salesday tonen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_salesday_preparation', 'menu.salesday.preparation', 'Mijn voorbereiding', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_salesday_agenda', 'menu.salesday.agenda', 'Mijn Agenda', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_salesday_team', 'menu.salesday.team', 'Mijn Team', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_salesday_stock', 'menu.salesday.stock', 'Mijn Voorraad', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_pst_enabled', 'menu.pst.enabled', 'PST tonen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_pst_dashboard', 'menu.pst.dashboard', 'Dashboard', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_pst_planning', 'menu.pst.planning', 'Planning', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_pst_segments', 'menu.pst.segments', 'Segmenten', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_pst_routes', 'menu.pst.routes', 'Routes', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_pst_prospecting', 'menu.pst.prospecting', 'Prospectie', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_contract_enabled', 'menu.contract.enabled', 'Contract tonen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_contract_open', 'menu.contract.open', 'Contracttool openen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_service_enabled', 'menu.service.enabled', 'Service tonen', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_service_my_day', 'menu.service.myDay', 'Mijn dag', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_service_planning', 'menu.service.planning', 'Planning', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
  ('perm_menu_service_interventions', 'menu.service.interventions', 'Interventies', 'Menu-rechten', 'Zichtbaarheid in het mega-menu.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE
  `label` = VALUES(`label`),
  `group` = VALUES(`group`),
  `description` = VALUES(`description`),
  `updatedAt` = CURRENT_TIMESTAMP(3);
