ALTER TABLE `User`
  MODIFY `role` ENUM('REPRESENTATIVE', 'SALES_LEADER', 'SALES_MANAGER', 'SERVICE_OPERATOR', 'COUNTRY_MANAGER', 'GROUP_MANAGER', 'ADMIN', 'SUPER_ADMIN') NOT NULL;

ALTER TABLE `RolePermission`
  MODIFY `role` ENUM('REPRESENTATIVE', 'SALES_LEADER', 'SALES_MANAGER', 'SERVICE_OPERATOR', 'COUNTRY_MANAGER', 'GROUP_MANAGER', 'ADMIN', 'SUPER_ADMIN') NOT NULL;

CREATE TABLE `UserCountryAccess` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `country` ENUM('BE', 'NL', 'DE') NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `UserCountryAccess_userId_country_key`(`userId`, `country`),
  INDEX `UserCountryAccess_country_idx`(`country`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `UserCountryAccess`
  ADD CONSTRAINT `UserCountryAccess_userId_fkey`
  FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
