CREATE TABLE `SalesArticle` (
  `id` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NOT NULL,
  `externalId` VARCHAR(191) NOT NULL,
  `sourceVersion` VARCHAR(191) NOT NULL,
  `sourceUpdatedAt` DATETIME(3) NOT NULL,
  `articleNumber` VARCHAR(191) NOT NULL,
  `stemNumber` VARCHAR(191) NULL,
  `descriptionNl` TEXT NOT NULL,
  `descriptionFr` TEXT NOT NULL,
  `descriptionDe` TEXT NOT NULL,
  `unit` VARCHAR(191) NOT NULL,
  `vatRate` DECIMAL(7,4) NOT NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `carrierBound` BOOLEAN NOT NULL DEFAULT false,
  `lotTrackingRequired` BOOLEAN NOT NULL DEFAULT false,
  `expiryTrackingRequired` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesArticle_provider_externalId_key` (`provider`, `externalId`),
  INDEX `SalesArticle_articleNumber_idx` (`articleNumber`),
  INDEX `SalesArticle_active_carrierBound_idx` (`active`, `carrierBound`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesArticlePrice` (
  `id` VARCHAR(191) NOT NULL,
  `articleId` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NOT NULL,
  `externalId` VARCHAR(191) NOT NULL,
  `sourceVersion` VARCHAR(191) NOT NULL,
  `sourceUpdatedAt` DATETIME(3) NOT NULL,
  `country` ENUM('BE', 'NL', 'DE') NOT NULL,
  `currency` VARCHAR(191) NOT NULL,
  `type` ENUM('SALES', 'CONTRACT') NOT NULL,
  `amount` DECIMAL(14,4) NOT NULL,
  `validFrom` DATE NOT NULL,
  `validUntil` DATE NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesArticlePrice_provider_externalId_key` (`provider`, `externalId`),
  INDEX `SalesArticlePrice_articleId_country_type_idx` (`articleId`, `country`, `type`),
  INDEX `SalesArticlePrice_country_type_validFrom_validUntil_idx` (`country`, `type`, `validFrom`, `validUntil`),
  CONSTRAINT `SalesArticlePrice_articleId_fkey` FOREIGN KEY (`articleId`) REFERENCES `SalesArticle` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesDocumentReason` (
  `id` VARCHAR(191) NOT NULL,
  `kind` ENUM('OVERRIDE', 'UNSIGNED_EXCEPTION') NOT NULL,
  `code` VARCHAR(191) NOT NULL,
  `labelNl` VARCHAR(191) NOT NULL,
  `labelFr` VARCHAR(191) NOT NULL,
  `labelDe` VARCHAR(191) NOT NULL,
  `country` ENUM('BE', 'NL', 'DE') NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `requiresComment` BOOLEAN NOT NULL DEFAULT true,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `SalesDocumentReason_kind_country_active_sortOrder_idx` (`kind`, `country`, `active`, `sortOrder`),
  INDEX `SalesDocumentReason_code_idx` (`code`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesDocumentNumberBlock` (
  `id` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NOT NULL,
  `externalId` VARCHAR(191) NULL,
  `country` ENUM('BE', 'NL', 'DE') NOT NULL,
  `documentType` ENUM('ORDER', 'ORDER_ALREADY_DELIVERED', 'INVOICE') NOT NULL,
  `prefix` VARCHAR(191) NOT NULL DEFAULT '',
  `firstSequence` INTEGER NOT NULL,
  `lastSequence` INTEGER NOT NULL,
  `nextSequence` INTEGER NOT NULL,
  `padding` INTEGER NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE', 'EXHAUSTED', 'CANCELLED', 'RECONCILED') NOT NULL DEFAULT 'ACTIVE',
  `sourceVersion` VARCHAR(191) NULL,
  `sourceUpdatedAt` DATETIME(3) NULL,
  `reservedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expiresAt` DATETIME(3) NULL,
  `reconciledAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `SalesDocumentNumberBlock_provider_country_documentType_status_idx` (`provider`, `country`, `documentType`, `status`),
  INDEX `SalesDocumentNumberBlock_externalId_idx` (`externalId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesDocumentNumberUse` (
  `id` VARCHAR(191) NOT NULL,
  `blockId` VARCHAR(191) NOT NULL,
  `number` VARCHAR(191) NOT NULL,
  `sequence` INTEGER NOT NULL,
  `status` ENUM('ALLOCATED', 'SUBMITTED', 'ACCEPTED', 'VOIDED', 'SKIPPED') NOT NULL DEFAULT 'ALLOCATED',
  `allocatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `submittedAt` DATETIME(3) NULL,
  `voidedAt` DATETIME(3) NULL,
  `skipReason` TEXT NULL,
  `reconciliationJson` LONGTEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesDocumentNumberUse_blockId_number_key` (`blockId`, `number`),
  UNIQUE INDEX `SalesDocumentNumberUse_blockId_sequence_key` (`blockId`, `sequence`),
  INDEX `SalesDocumentNumberUse_status_allocatedAt_idx` (`status`, `allocatedAt`),
  CONSTRAINT `SalesDocumentNumberUse_blockId_fkey` FOREIGN KEY (`blockId`) REFERENCES `SalesDocumentNumberBlock` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesDocument` (
  `id` VARCHAR(191) NOT NULL,
  `appointmentId` VARCHAR(191) NOT NULL,
  `relationId` VARCHAR(191) NOT NULL,
  `representativeUserId` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NOT NULL,
  `documentType` ENUM('ORDER', 'ORDER_ALREADY_DELIVERED', 'INVOICE') NOT NULL,
  `proposedDocumentType` ENUM('ORDER', 'ORDER_ALREADY_DELIVERED', 'INVOICE') NOT NULL,
  `status` ENUM('QUEUED', 'ACCEPTED', 'REJECTED', 'VOIDED') NOT NULL DEFAULT 'QUEUED',
  `deliveryStatus` ENUM('PENDING_ERP', 'SENT_TO_CUSTOMER', 'FAILED') NOT NULL DEFAULT 'PENDING_ERP',
  `documentNumber` VARCHAR(191) NOT NULL,
  `numberUseId` VARCHAR(191) NOT NULL,
  `businessDate` DATE NOT NULL,
  `documentDate` DATE NOT NULL,
  `currency` VARCHAR(191) NOT NULL,
  `language` ENUM('nl', 'fr', 'de') NOT NULL,
  `templateVersion` VARCHAR(191) NOT NULL,
  `customerSnapshotJson` LONGTEXT NOT NULL,
  `billingSnapshotJson` LONGTEXT NULL,
  `renderedDocumentHtml` LONGTEXT NOT NULL,
  `renderedDocumentSha256` CHAR(64) NOT NULL,
  `contentFingerprint` CHAR(64) NOT NULL,
  `amountExcludingVat` DECIMAL(16,4) NOT NULL,
  `vatAmount` DECIMAL(16,4) NOT NULL,
  `amountIncludingVat` DECIMAL(16,4) NOT NULL,
  `overrideReasonId` VARCHAR(191) NULL,
  `overrideComment` TEXT NULL,
  `commandId` VARCHAR(191) NOT NULL,
  `externalId` VARCHAR(191) NULL,
  `sourceVersion` VARCHAR(191) NULL,
  `erpAcknowledgedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesDocument_documentNumber_key` (`documentNumber`),
  UNIQUE INDEX `SalesDocument_numberUseId_key` (`numberUseId`),
  UNIQUE INDEX `SalesDocument_commandId_key` (`commandId`),
  INDEX `SalesDocument_appointmentId_createdAt_idx` (`appointmentId`, `createdAt`),
  INDEX `SalesDocument_relationId_documentDate_idx` (`relationId`, `documentDate`),
  INDEX `SalesDocument_representativeUserId_businessDate_idx` (`representativeUserId`, `businessDate`),
  INDEX `SalesDocument_status_createdAt_idx` (`status`, `createdAt`),
  INDEX `SalesDocument_deliveryStatus_createdAt_idx` (`deliveryStatus`, `createdAt`),
  CONSTRAINT `SalesDocument_appointmentId_fkey` FOREIGN KEY (`appointmentId`) REFERENCES `SalesAppointment` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesDocument_relationId_fkey` FOREIGN KEY (`relationId`) REFERENCES `BusinessRelation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesDocument_representativeUserId_fkey` FOREIGN KEY (`representativeUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesDocument_numberUseId_fkey` FOREIGN KEY (`numberUseId`) REFERENCES `SalesDocumentNumberUse` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesDocument_overrideReasonId_fkey` FOREIGN KEY (`overrideReasonId`) REFERENCES `SalesDocumentReason` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesDocumentLine` (
  `id` VARCHAR(191) NOT NULL,
  `documentId` VARCHAR(191) NOT NULL,
  `lineNumber` INTEGER NOT NULL,
  `articleId` VARCHAR(191) NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `articleNumberSnapshot` VARCHAR(191) NOT NULL,
  `descriptionSnapshot` TEXT NOT NULL,
  `quantity` DECIMAL(14,3) NOT NULL,
  `unitSnapshot` VARCHAR(191) NOT NULL,
  `unitPriceSnapshot` DECIMAL(14,4) NOT NULL,
  `vatRateSnapshot` DECIMAL(7,4) NOT NULL,
  `lineAmountExcludingVat` DECIMAL(16,4) NOT NULL,
  `lineVatAmount` DECIMAL(16,4) NOT NULL,
  `lineAmountIncludingVat` DECIMAL(16,4) NOT NULL,
  `representativeStockQuantitySnapshot` DECIMAL(14,3) NULL,
  `representativeStockImpactQuantity` DECIMAL(14,3) NOT NULL,
  `carrierRequired` BOOLEAN NOT NULL DEFAULT false,
  `customerCarrierExternalId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesDocumentLine_documentId_lineNumber_key` (`documentId`, `lineNumber`),
  INDEX `SalesDocumentLine_articleExternalId_idx` (`articleExternalId`),
  INDEX `SalesDocumentLine_customerCarrierExternalId_idx` (`customerCarrierExternalId`),
  CONSTRAINT `SalesDocumentLine_documentId_fkey` FOREIGN KEY (`documentId`) REFERENCES `SalesDocument` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SalesDocumentLine_articleId_fkey` FOREIGN KEY (`articleId`) REFERENCES `SalesArticle` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesDocumentSignatureEvidence` (
  `id` VARCHAR(191) NOT NULL,
  `documentId` VARCHAR(191) NOT NULL,
  `status` ENUM('SIGNED', 'UNSIGNED_EXCEPTION') NOT NULL,
  `signedByName` VARCHAR(191) NULL,
  `signedAt` DATETIME(3) NOT NULL,
  `signatureData` LONGTEXT NULL,
  `signatureSha256` CHAR(64) NULL,
  `exceptionReasonId` VARCHAR(191) NULL,
  `exceptionComment` TEXT NULL,
  `documentSha256` CHAR(64) NOT NULL,
  `signatureContextJson` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesDocumentSignatureEvidence_documentId_key` (`documentId`),
  INDEX `SalesDocumentSignatureEvidence_status_signedAt_idx` (`status`, `signedAt`),
  INDEX `SalesDocumentSignatureEvidence_exceptionReasonId_idx` (`exceptionReasonId`),
  CONSTRAINT `SalesDocumentSignatureEvidence_documentId_fkey` FOREIGN KEY (`documentId`) REFERENCES `SalesDocument` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesDocumentSignatureEvidence_exceptionReasonId_fkey` FOREIGN KEY (`exceptionReasonId`) REFERENCES `SalesDocumentReason` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
