CREATE TABLE `InventoryReason` (
  `id` VARCHAR(191) NOT NULL,
  `kind` ENUM('ARCHIVE', 'CARRIER_COUNT_DISCREPANCY', 'RECEIPT_DISCREPANCY') NOT NULL,
  `code` VARCHAR(191) NOT NULL,
  `labelNl` VARCHAR(191) NOT NULL,
  `labelFr` VARCHAR(191) NOT NULL,
  `labelDe` VARCHAR(191) NOT NULL,
  `country` ENUM('BE', 'NL', 'DE') NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `requiresComment` BOOLEAN NOT NULL DEFAULT true,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `InventoryReason_kind_country_active_sortOrder_idx` (`kind`, `country`, `active`, `sortOrder`),
  INDEX `InventoryReason_code_idx` (`code`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryLocation` (
  `id` VARCHAR(191) NOT NULL,
  `type` ENUM('CENTRAL_WAREHOUSE', 'TRANSIT', 'REPRESENTATIVE_VEHICLE', 'CUSTOMER_LOCATION', 'CUSTOMER_SUBLOCATION', 'CUSTOMER_CARRIER', 'QUARANTINE') NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NULL,
  `externalId` VARCHAR(191) NULL,
  `sourceVersion` VARCHAR(191) NULL,
  `sourceUpdatedAt` DATETIME(3) NULL,
  `systemKey` VARCHAR(191) NULL,
  `country` ENUM('BE', 'NL', 'DE') NOT NULL,
  `relationId` VARCHAR(191) NULL,
  `representativeUserId` VARCHAR(191) NULL,
  `parentId` VARCHAR(191) NULL,
  `name` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `linkedArticleExternalId` VARCHAR(191) NULL,
  `archived` BOOLEAN NOT NULL DEFAULT false,
  `archiveReasonId` VARCHAR(191) NULL,
  `archiveComment` TEXT NULL,
  `archivedAt` DATETIME(3) NULL,
  `commandId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryLocation_systemKey_key` (`systemKey`),
  UNIQUE INDEX `InventoryLocation_commandId_key` (`commandId`),
  UNIQUE INDEX `InventoryLocation_provider_externalId_key` (`provider`, `externalId`),
  INDEX `InventoryLocation_type_country_archived_idx` (`type`, `country`, `archived`),
  INDEX `InventoryLocation_relationId_type_archived_idx` (`relationId`, `type`, `archived`),
  INDEX `InventoryLocation_representativeUserId_type_archived_idx` (`representativeUserId`, `type`, `archived`),
  INDEX `InventoryLocation_parentId_type_archived_idx` (`parentId`, `type`, `archived`),
  CONSTRAINT `InventoryLocation_relationId_fkey` FOREIGN KEY (`relationId`) REFERENCES `BusinessRelation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryLocation_representativeUserId_fkey` FOREIGN KEY (`representativeUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryLocation_parentId_fkey` FOREIGN KEY (`parentId`) REFERENCES `InventoryLocation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryLocation_archiveReasonId_fkey` FOREIGN KEY (`archiveReasonId`) REFERENCES `InventoryReason` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryBalance` (
  `id` VARCHAR(191) NOT NULL,
  `balanceKey` VARCHAR(191) NOT NULL,
  `locationId` VARCHAR(191) NOT NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `unit` VARCHAR(191) NOT NULL,
  `quantity` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `lotNumber` VARCHAR(191) NULL,
  `expiryDate` DATE NULL,
  `sourceVersion` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryBalance_balanceKey_key` (`balanceKey`),
  INDEX `InventoryBalance_locationId_articleExternalId_idx` (`locationId`, `articleExternalId`),
  INDEX `InventoryBalance_articleExternalId_idx` (`articleExternalId`),
  INDEX `InventoryBalance_expiryDate_idx` (`expiryDate`),
  CONSTRAINT `InventoryBalance_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `InventoryLocation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryReplenishment` (
  `id` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NOT NULL,
  `externalId` VARCHAR(191) NOT NULL,
  `sourceVersion` VARCHAR(191) NOT NULL,
  `sourceUpdatedAt` DATETIME(3) NOT NULL,
  `shipmentNumber` VARCHAR(191) NULL,
  `status` ENUM('IN_TRANSIT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED') NOT NULL DEFAULT 'IN_TRANSIT',
  `country` ENUM('BE', 'NL', 'DE') NOT NULL,
  `representativeUserId` VARCHAR(191) NOT NULL,
  `representativeExternalId` VARCHAR(191) NOT NULL,
  `transitLocationId` VARCHAR(191) NULL,
  `shippedAt` DATETIME(3) NULL,
  `expectedAt` DATETIME(3) NULL,
  `receivedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryReplenishment_provider_externalId_key` (`provider`, `externalId`),
  INDEX `InventoryReplenishment_representativeUserId_status_expectedAt_idx` (`representativeUserId`, `status`, `expectedAt`),
  INDEX `InventoryReplenishment_country_status_idx` (`country`, `status`),
  CONSTRAINT `InventoryReplenishment_representativeUserId_fkey` FOREIGN KEY (`representativeUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryReplenishment_transitLocationId_fkey` FOREIGN KEY (`transitLocationId`) REFERENCES `InventoryLocation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryReplenishmentLine` (
  `id` VARCHAR(191) NOT NULL,
  `replenishmentId` VARCHAR(191) NOT NULL,
  `externalId` VARCHAR(191) NOT NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `articleNumberSnapshot` VARCHAR(191) NULL,
  `descriptionSnapshot` TEXT NULL,
  `expectedQuantity` DECIMAL(14,3) NOT NULL,
  `receivedQuantity` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `damagedQuantity` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(191) NOT NULL,
  `lotNumber` VARCHAR(191) NULL,
  `expiryDate` DATE NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryReplenishmentLine_replenishmentId_externalId_key` (`replenishmentId`, `externalId`),
  INDEX `InventoryReplenishmentLine_articleExternalId_idx` (`articleExternalId`),
  CONSTRAINT `InventoryReplenishmentLine_replenishmentId_fkey` FOREIGN KEY (`replenishmentId`) REFERENCES `InventoryReplenishment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryReceipt` (
  `id` VARCHAR(191) NOT NULL,
  `receiptKey` VARCHAR(191) NOT NULL,
  `replenishmentId` VARCHAR(191) NOT NULL,
  `actorUserId` VARCHAR(191) NOT NULL,
  `status` ENUM('SUBMITTED', 'ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'SUBMITTED',
  `receivedAt` DATETIME(3) NOT NULL,
  `comment` TEXT NULL,
  `commandId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryReceipt_receiptKey_key` (`receiptKey`),
  UNIQUE INDEX `InventoryReceipt_commandId_key` (`commandId`),
  INDEX `InventoryReceipt_replenishmentId_receivedAt_idx` (`replenishmentId`, `receivedAt`),
  INDEX `InventoryReceipt_actorUserId_receivedAt_idx` (`actorUserId`, `receivedAt`),
  CONSTRAINT `InventoryReceipt_replenishmentId_fkey` FOREIGN KEY (`replenishmentId`) REFERENCES `InventoryReplenishment` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryReceipt_actorUserId_fkey` FOREIGN KEY (`actorUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryReceiptLine` (
  `id` VARCHAR(191) NOT NULL,
  `receiptId` VARCHAR(191) NOT NULL,
  `replenishmentLineId` VARCHAR(191) NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `articleNumberSnapshot` VARCHAR(191) NULL,
  `receivedQuantity` DECIMAL(14,3) NOT NULL,
  `damagedQuantity` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `excessQuantity` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `unit` VARCHAR(191) NOT NULL,
  `lotNumber` VARCHAR(191) NULL,
  `expiryDate` DATE NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `InventoryReceiptLine_receiptId_idx` (`receiptId`),
  INDEX `InventoryReceiptLine_replenishmentLineId_idx` (`replenishmentLineId`),
  INDEX `InventoryReceiptLine_articleExternalId_idx` (`articleExternalId`),
  CONSTRAINT `InventoryReceiptLine_receiptId_fkey` FOREIGN KEY (`receiptId`) REFERENCES `InventoryReceipt` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `InventoryReceiptLine_replenishmentLineId_fkey` FOREIGN KEY (`replenishmentLineId`) REFERENCES `InventoryReplenishmentLine` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryReceiptEvidence` (
  `id` VARCHAR(191) NOT NULL,
  `receiptId` VARCHAR(191) NOT NULL,
  `type` ENUM('REPRESENTATIVE_SIGNATURE', 'PHOTO') NOT NULL,
  `signerName` VARCHAR(191) NULL,
  `signatureData` LONGTEXT NULL,
  `storageKey` VARCHAR(191) NULL,
  `mimeType` VARCHAR(191) NULL,
  `contentSha256` CHAR(64) NULL,
  `capturedAt` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `InventoryReceiptEvidence_receiptId_type_idx` (`receiptId`, `type`),
  CONSTRAINT `InventoryReceiptEvidence_receiptId_fkey` FOREIGN KEY (`receiptId`) REFERENCES `InventoryReceipt` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryDiscrepancy` (
  `id` VARCHAR(191) NOT NULL,
  `receiptId` VARCHAR(191) NOT NULL,
  `receiptLineId` VARCHAR(191) NULL,
  `type` ENUM('SHORTAGE', 'EXCESS', 'DAMAGE') NOT NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `quantity` DECIMAL(14,3) NOT NULL,
  `unit` VARCHAR(191) NOT NULL,
  `reasonId` VARCHAR(191) NULL,
  `comment` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `InventoryDiscrepancy_receiptId_type_idx` (`receiptId`, `type`),
  INDEX `InventoryDiscrepancy_articleExternalId_idx` (`articleExternalId`),
  INDEX `InventoryDiscrepancy_reasonId_idx` (`reasonId`),
  CONSTRAINT `InventoryDiscrepancy_receiptId_fkey` FOREIGN KEY (`receiptId`) REFERENCES `InventoryReceipt` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `InventoryDiscrepancy_receiptLineId_fkey` FOREIGN KEY (`receiptLineId`) REFERENCES `InventoryReceiptLine` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `InventoryDiscrepancy_reasonId_fkey` FOREIGN KEY (`reasonId`) REFERENCES `InventoryReason` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryConsumablesRequest` (
  `id` VARCHAR(191) NOT NULL,
  `requestKey` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'BC_NAV', 'ODOO') NOT NULL,
  `country` ENUM('BE', 'NL', 'DE') NOT NULL,
  `actorUserId` VARCHAR(191) NOT NULL,
  `representativeExternalId` VARCHAR(191) NOT NULL,
  `status` ENUM('SUBMITTED', 'ACCEPTED', 'REJECTED', 'FULFILLED') NOT NULL DEFAULT 'SUBMITTED',
  `businessDate` DATE NOT NULL,
  `submittedAt` DATETIME(3) NOT NULL,
  `commandId` VARCHAR(191) NOT NULL,
  `externalId` VARCHAR(191) NULL,
  `sourceVersion` VARCHAR(191) NULL,
  `erpStatusUpdatedAt` DATETIME(3) NULL,
  `comment` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryConsumablesRequest_requestKey_key` (`requestKey`),
  UNIQUE INDEX `InventoryConsumablesRequest_commandId_key` (`commandId`),
  INDEX `InventoryConsumablesRequest_actorUserId_businessDate_idx` (`actorUserId`, `businessDate`),
  INDEX `InventoryConsumablesRequest_provider_externalId_idx` (`provider`, `externalId`),
  INDEX `InventoryConsumablesRequest_status_submittedAt_idx` (`status`, `submittedAt`),
  CONSTRAINT `InventoryConsumablesRequest_actorUserId_fkey` FOREIGN KEY (`actorUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryConsumablesRequestLine` (
  `id` VARCHAR(191) NOT NULL,
  `requestId` VARCHAR(191) NOT NULL,
  `lineNumber` INTEGER NOT NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `articleNumberSnapshot` VARCHAR(191) NULL,
  `descriptionSnapshot` TEXT NULL,
  `quantity` DECIMAL(14,3) NOT NULL,
  `unit` VARCHAR(191) NOT NULL,
  `comment` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryConsumablesRequestLine_requestId_lineNumber_key` (`requestId`, `lineNumber`),
  INDEX `InventoryConsumablesRequestLine_articleExternalId_idx` (`articleExternalId`),
  CONSTRAINT `InventoryConsumablesRequestLine_requestId_fkey` FOREIGN KEY (`requestId`) REFERENCES `InventoryConsumablesRequest` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryCarrierCount` (
  `id` VARCHAR(191) NOT NULL,
  `countKey` VARCHAR(191) NOT NULL,
  `carrierLocationId` VARCHAR(191) NOT NULL,
  `actorUserId` VARCHAR(191) NOT NULL,
  `status` ENUM('SUBMITTED', 'ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'SUBMITTED',
  `countedAt` DATETIME(3) NOT NULL,
  `commandId` VARCHAR(191) NOT NULL,
  `comment` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryCarrierCount_countKey_key` (`countKey`),
  UNIQUE INDEX `InventoryCarrierCount_commandId_key` (`commandId`),
  INDEX `InventoryCarrierCount_carrierLocationId_countedAt_idx` (`carrierLocationId`, `countedAt`),
  INDEX `InventoryCarrierCount_actorUserId_countedAt_idx` (`actorUserId`, `countedAt`),
  CONSTRAINT `InventoryCarrierCount_carrierLocationId_fkey` FOREIGN KEY (`carrierLocationId`) REFERENCES `InventoryLocation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryCarrierCount_actorUserId_fkey` FOREIGN KEY (`actorUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryCarrierCountLine` (
  `id` VARCHAR(191) NOT NULL,
  `countId` VARCHAR(191) NOT NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `articleNumberSnapshot` VARCHAR(191) NULL,
  `systemQuantity` DECIMAL(14,3) NOT NULL,
  `countedQuantity` DECIMAL(14,3) NOT NULL,
  `differenceQuantity` DECIMAL(14,3) NOT NULL,
  `unit` VARCHAR(191) NOT NULL,
  `lotNumber` VARCHAR(191) NULL,
  `expiryDate` DATE NULL,
  `reasonId` VARCHAR(191) NULL,
  `reasonComment` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `InventoryCarrierCountLine_countId_idx` (`countId`),
  INDEX `InventoryCarrierCountLine_articleExternalId_idx` (`articleExternalId`),
  INDEX `InventoryCarrierCountLine_reasonId_idx` (`reasonId`),
  CONSTRAINT `InventoryCarrierCountLine_countId_fkey` FOREIGN KEY (`countId`) REFERENCES `InventoryCarrierCount` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `InventoryCarrierCountLine_reasonId_fkey` FOREIGN KEY (`reasonId`) REFERENCES `InventoryReason` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InventoryMovement` (
  `id` VARCHAR(191) NOT NULL,
  `movementKey` VARCHAR(191) NOT NULL,
  `type` ENUM('ERP_REPLENISHMENT_TRANSIT', 'REPLENISHMENT_RECEIPT', 'REPLENISHMENT_DAMAGED_QUARANTINE', 'SALES_DELIVERY', 'SALES_CARRIER_DELIVERY', 'CARRIER_COUNT_CORRECTION', 'ERP_CORRECTION') NOT NULL,
  `status` ENUM('APPLIED', 'VOIDED') NOT NULL DEFAULT 'APPLIED',
  `actorUserId` VARCHAR(191) NULL,
  `fromLocationId` VARCHAR(191) NULL,
  `toLocationId` VARCHAR(191) NULL,
  `articleExternalId` VARCHAR(191) NOT NULL,
  `articleNumberSnapshot` VARCHAR(191) NULL,
  `quantity` DECIMAL(14,3) NOT NULL,
  `unit` VARCHAR(191) NOT NULL,
  `lotNumber` VARCHAR(191) NULL,
  `expiryDate` DATE NULL,
  `sourceDocumentLineId` VARCHAR(191) NULL,
  `replenishmentReceiptLineId` VARCHAR(191) NULL,
  `carrierCountLineId` VARCHAR(191) NULL,
  `reasonId` VARCHAR(191) NULL,
  `reasonComment` TEXT NULL,
  `commandId` VARCHAR(191) NULL,
  `occurredAt` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `InventoryMovement_movementKey_key` (`movementKey`),
  INDEX `InventoryMovement_fromLocationId_occurredAt_idx` (`fromLocationId`, `occurredAt`),
  INDEX `InventoryMovement_toLocationId_occurredAt_idx` (`toLocationId`, `occurredAt`),
  INDEX `InventoryMovement_articleExternalId_occurredAt_idx` (`articleExternalId`, `occurredAt`),
  INDEX `InventoryMovement_sourceDocumentLineId_idx` (`sourceDocumentLineId`),
  INDEX `InventoryMovement_replenishmentReceiptLineId_idx` (`replenishmentReceiptLineId`),
  INDEX `InventoryMovement_carrierCountLineId_idx` (`carrierCountLineId`),
  INDEX `InventoryMovement_commandId_idx` (`commandId`),
  CONSTRAINT `InventoryMovement_actorUserId_fkey` FOREIGN KEY (`actorUserId`) REFERENCES `User` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `InventoryMovement_fromLocationId_fkey` FOREIGN KEY (`fromLocationId`) REFERENCES `InventoryLocation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryMovement_toLocationId_fkey` FOREIGN KEY (`toLocationId`) REFERENCES `InventoryLocation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryMovement_sourceDocumentLineId_fkey` FOREIGN KEY (`sourceDocumentLineId`) REFERENCES `SalesDocumentLine` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryMovement_replenishmentReceiptLineId_fkey` FOREIGN KEY (`replenishmentReceiptLineId`) REFERENCES `InventoryReceiptLine` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryMovement_carrierCountLineId_fkey` FOREIGN KEY (`carrierCountLineId`) REFERENCES `InventoryCarrierCountLine` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `InventoryMovement_reasonId_fkey` FOREIGN KEY (`reasonId`) REFERENCES `InventoryReason` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
