CREATE TABLE `SalesAttachment` (
  `id` VARCHAR(191) NOT NULL,
  `targetType` ENUM('APPOINTMENT', 'CUSTOMER') NOT NULL,
  `status` ENUM('STAGED', 'ACCEPTED', 'REJECTED', 'FAILED') NOT NULL DEFAULT 'STAGED',
  `appointmentId` VARCHAR(191) NULL,
  `relationId` VARCHAR(191) NULL,
  `authorUserId` VARCHAR(191) NOT NULL,
  `deviceId` VARCHAR(191) NOT NULL,
  `categoryExternalId` VARCHAR(191) NOT NULL,
  `fileName` VARCHAR(191) NOT NULL,
  `storageKey` VARCHAR(191) NOT NULL,
  `mimeType` VARCHAR(191) NOT NULL,
  `sizeBytes` INTEGER NOT NULL,
  `sha256` VARCHAR(191) NOT NULL,
  `uploadToken` VARCHAR(191) NOT NULL,
  `commandId` VARCHAR(191) NOT NULL,
  `externalId` VARCHAR(191) NULL,
  `erpAcknowledgedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `SalesAttachment_storageKey_key` (`storageKey`),
  UNIQUE INDEX `SalesAttachment_uploadToken_key` (`uploadToken`),
  UNIQUE INDEX `SalesAttachment_commandId_key` (`commandId`),
  INDEX `SalesAttachment_appointmentId_createdAt_idx` (`appointmentId`, `createdAt`),
  INDEX `SalesAttachment_relationId_createdAt_idx` (`relationId`, `createdAt`),
  INDEX `SalesAttachment_authorUserId_createdAt_idx` (`authorUserId`, `createdAt`),
  INDEX `SalesAttachment_status_createdAt_idx` (`status`, `createdAt`),
  CONSTRAINT `SalesAttachment_appointmentId_fkey` FOREIGN KEY (`appointmentId`) REFERENCES `SalesAppointment` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesAttachment_relationId_fkey` FOREIGN KEY (`relationId`) REFERENCES `BusinessRelation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesAttachment_authorUserId_fkey` FOREIGN KEY (`authorUserId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
